src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="articleId", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="date")
     */
    private $publication_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $emergency;

    /**
     * @ORM\OneToMany(targetEntity=Pictures::class, mappedBy="articles", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;


    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $genre;

    /**
     * @ORM\ManyToOne(targetEntity=Journalist::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $journalist;



    public function __construct()
    {
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): self
    {
        $this->publication_date = $publication_date;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;
        return $this;
    }

    public function getEmergency(): ?bool
    {
        return $this->emergency;
    }

    public function setEmergency(bool $emergency): self
    {
        $this->emergency = $emergency;
        return $this;
    }

    /**
     * @return Collection|Pictures[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture  (Pictures $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setArticle($this);
        }
        return $this;
    }

    public function removePicture(Pictures $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getArticle() === $this) {
                $picture->setArticle(null);
            }
        }

        return $this;
    }

    public function setPicture(string $string)
    {
    }


    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment  $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getJournalist(): ?Journalist
    {
        return $this->journalist;
    }

    public function setJournalist(?Journalist $journalist): self
    {
        $this->journalist = $journalist;

        return $this;
    }


}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="comments")
     */
    private $articleId;


    /**
     * @ORM\Column(type="boolean")
     */
    private $active = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nickname;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $rgpd = null;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity=Comment::class, inversedBy="replies")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="parent")
     */
    private $replies;

    public function __construct()
    {
        $this->replies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticleId(): Collection
    {
        return $this->articleId;
    }

    public function addArticleId(Article $articleId): self
    {
        if (!$this->articleId->contains($articleId)) {
            $this->articleId[] = $articleId;
            $articleId->setComment($this);
        }

        return $this;
    }

    public function removeArticleId(Article $articleId): self
    {
        if ($this->articleId->removeElement($articleId)) {
            // set the owning side to null (unless already changed)
            if ($articleId->getComment() === $this) {
                $articleId->setComment(null);
            }
        }

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getArticlId(): ?Article
    {
        return $this->articlId;
    }

    public function setArticlId(?Article $articlId): self
    {
        $this->articlId = $articlId;

        return $this;
    }


    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getRgpd(): ?bool
    {
        return $this->rgpd;
    }

    public function setRgpd(bool $rgpd): self
    {
        $this->rgpd = $rgpd;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getReplies(): Collection
    {
        return $this->replies;
    }

    public function addReply(self $reply): self
    {
        if (!$this->replies->contains($reply)) {
            $this->replies[] = $reply;
            $reply->setParent($this);
        }

        return $this;
    }

    public function removeReply(self $reply): self
    {
        if ($this->replies->removeElement($reply)) {
            // set the owning side to null (unless already changed)
            if ($reply->getParent() === $this) {
                $reply->setParent(null);
            }
        }

        return $this;
    }
}

src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EvenentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenentRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $spaceAvailable;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="evenents")
     * @ORM\JoinColumn(nullable=true)
     */
    private $User;


    public function __construct()
    {
        $this->Participant = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSpaceAvailable(): ?string
    {
        return $this->spaceAvailable;
    }

    public function setSpaceAvailable(string $spaceAvailable): self
    {
        $this->spaceAvailable = $spaceAvailable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Entity\Article;
use App\Entity\Message;
use App\Form\SearchForm;
use App\Form\ArticleType;
use App\Form\Form1Type;
use App\Repository\ArticleRepository;
use App\Repository\EvenentRepository;
use App\Repository\MessageRepository;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


use function Sodium\add;

class AccueilController extends AbstractController
{

    private $articleRepository;
    private $events;
    private $msg;

    public function __construct(ArticleRepository $articleRepository, EvenentRepository $events, MessageRepository $msg)
    {
        $this->articleRepository = $articleRepository;
        $this->events = $events;
        $this->msg = $msg;

    }

    /**
     * @Route("/", name="choose")
     */
    public function choose()
    {
        return $this->render('accueil/choose.html.twig');
    }

    /**
     * @Route("/home", name="home")
     */
    public function home(Request $request, ObjectManager $manager): Response
    {
        $emergency = $this->articleRepository->findBy(array('emergency' => true));
        $Events = $this->events->findall();

        $data = new SearchData();
        $formSearch = $this->createForm(SearchForm::class, $data);
        $formSearch->handleRequest($request);
        $article = $this->articleRepository->findSearch($data);

        $message = new Message();
        $form = $this->createForm(Form1Type::class, $message);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            $manager->persist($message);
            $manager->flush();
            return $this->redirectToRoute('msgSend',['id' =>$message->getId()]);
        }

        return $this->render('accueil/home.html.twig', [
            'emergency' => $emergency,
            'articles' => $article,
            'Events' => $Events,
            'formMessage' => $form->createView(),
            'formSearch' => $formSearch->createView()

        ]);
  }

    /**
     * @Route("msgSend", name="msgSend")
     */
    public  function msgSend(){
        return $this->render('accueil/msgSend.html.twig');
    }


}

templates/accueil/choose.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Welcome to WH ?</title>
    <link href="{{'choix.css'}}" type="text/css" rel="stylesheet">
</head>

<body>
<div class="center">
    <div class="titre">
        <div class="title">
            <h2>Welcome to</h2>
            <div class="trait"></div>
            <h1>What Happened ?</h1>
        </div>
    </div>
        <table class="choices">
            <tr>
                <td>
                    <div class="connection">
                        <p> Want u write something ?</p>
                        <button><a href="{{ path('login') }}">Sign in</a></button>
                    </div>
                </td>
                <td>
                </td>
                <td>
                    <div class="inscription">
                        <p>Want to become a member ?</p>
                        <button><a href="{{ path('app_register') }}">Sign up</a></button>
                    </div>
                </td>
            </tr>
            <tr>
                <td>

                </td>
                <td>
                    <div class="visit">
                        <p>Need to know more about us ?</p>
                        <button><a href="{{ path('home') }}">Visit</a></button>
                    </div>
                </td>
                <td>
                </td>
            </tr>
        </table>
</div>
</body>
</html>

templates/accueil/home.html.twig
{% extends 'base.html.twig' %}
{% block body%}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }
        window.onclick = function(event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>

    <div class="body_head">
        <img id="business" src="pictures/business.jpg" alt=""/>
    </div>
    <h1>What happened ?</h1>
    <h2>"If you know something, Say it."</h2>

    {# -----------------------------------------Menu horizontal----------------------------------------------#}

        <ul>
            <li class="laUne">
                <button type="button" class="btn btn-primary"><div class="texte">A la une</div></button>
            </li>
            <li>
                <button type="button" class="btn btn-primary"><div class="texte">Sciences</div></button>
                </li>
            <li>
                <button type="button" class="btn btn-primary"><div class="texte">Histoire</div></button>
            </li>
            <li>
                <button type="button" class="btn btn-primary"><div class="texte">Sport</div></button>
            </li>
            <li>
                <button type="button" class="btn btn-primary"><div class="texte">Politiquue</div></button>
            </li>
            <li>
                <button type="button" class="btn btn-primary"><div class="texte">À propos</div></button>
            </li>
            <li>
                {{ form_start(formSearch, {'attr':{'class':'form-inline my-2 my-lg-0'}}) }}
                    {{ form_widget(formSearch.q) }}
                    <input type="image" id="search" class="btn btn-primary" src="pictures/loupe.png" alt="">
                {{ form_end(formSearch) }}
            </li>
            <li>
                <div class="dropdown">
                    <input onclick="myFunction()" type="image" id="img_profil" class="dropbtn"
                           src="pictures/profil.png" alt="">
                    <div id="myDropdown" class="dropdown-content">
                        {% if app.user %}
                            <a href="{{ path('logout') }}">se déconnecter</a>
                            <a href="{{ path('profile') }}">Voir mon profil</a>
                        {% else %}
                            <a href="{{ path('login') }}">se connecter</a>
                        {% endif %}
                    </div>
                </div>
            </li>
        </ul>

    {# ----------------------------------------------Evenements---------------------------------------------------- #}

    <div id="corp"  class="p-3 mb-2 bg-primary text-white">
        <div id="d_right" >
            <div >
                <p>Our events</p>
                {% include 'accueil/Events.html.twig' %}
            </div>
        </div>

        <div id="d_center">
            {% for article in articles %}
                <section id ="art" class="articles">
                    <article>
                        <h3> {{ article.title }} numéro {{ article.id }}</h3>
                        <div class="metadata"> ecrit le {{ article.publicationdate | date('Y/m/d')}}
                            a {{ article.publicationdate | date('H:i')}} dans la categorie scientifique </div>
                        <div class ="content">
                            <P> voila le paragraphe de mon article</P>
                        </div>
                        {% for image in article.pictures %}
                            <div>
                                <img src="{{ asset('/uploads/') ~ image.name}}" alt="image" width="400" height="300">
                            </div>
                        {% endfor %}
                        <a href="{{ path('article_show', {'id': article.id}) }}" class="btn btn-primary">Lire la suite</a>
                    </article>
                </section>
            {% endfor %}
        </div>

        <div id="d_right" >
            {% include 'accueil/message.html.twig' %}
            <div>
                {% include 'accueil/emergency.html.twig' %}
            </div>
        </div>

    </div>

{% endblock%}

templates/accueil/message.html.twig
<!DOCTYPE>
<html>
{#
{% form_theme formMessage 'bootstrap_4_layout.html.twig' %} #}
<head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{{ 'Message.css' }}" type="text/css">
</head>

{% block body %}

        <p> You want to talk us ? Please write here </p>

        {{ form_start(formMessage) }}
        <table>
                <tr>
                        <td>Name</td>
                        <td>{{ form_widget(formMessage.name,{'attr':{ 'placeholder':"Name", 'class':'name'}}) }}</td>
                </tr>
                <tr>
                        <td>first name</td>
                        <td>{{ form_widget(formMessage.fist_name,{'attr':{ 'placeholder': "First Name", 'class':'index'}}) }}</td>
                </tr>
                <tr>
                        <td>Date</td>
                        <td>{{ form_widget(formMessage.date,{'attr':{ 'placeholder':"Date", 'class':'date'}}) }}</td>
                </tr>
                <tr>
                        <td>Email</td>
                        <td>{{ form_widget(formMessage.email,{'attr':{ 'placeholder': "Email", 'class':'index'}}) }}</td>
                </tr>
                <tr>
                        <td>Message</td>
                        <td>{{ form_widget(formMessage.content,{'attr':{'placeholder': "Message"}} )}}</td>
                </tr>
                <tr>
                        <td></td>
                        <td><button type="submit" class="btn btn-success">Envoyer</button></td>
                </tr>
        </table>


        {{ form_end (formMessage) }}

{% endblock %}
</html>

templates/accueil/msgReçu.html.twig
{% block body %}
    <p> Write Here</p>

    {% for message in messages %}
        <tr>
            <td>{{ message.id }}</td>
            <td>{{ message.name }}</td>
            <td>{{ message.fistname }}</td>
            <td>{{ message.email }}</td>
            <td>{{ message.date ? message.date|date('Y-m-d') : '' }}</td>
            <td>{{ message.content }}</td>

        </tr>
    {% else %}
        <tr>
            <td colspan="6">no records found</td>
        </tr>
    {% endfor %}

{% endblock %}

templates/accueil/registration.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <title>{% block title %}{% endblock %}</title>

        <h1 id="rens"> Veuillez renseigner les champs </h1>

{% endblock %}

templates/accueil/showArticle.html.twig


{% extends 'base.html.twig' %}
{% block body %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{{ asset('js/recup_comment.js') }}"></script>
<script>
    function myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }
    window.onclick = function(event) {
        if (!event.target.matches('.dropbtn')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>

<div class="body_head">
    <img id="business" src="pictures/business.jpg" alt=""/>
</div>
<h1>What happened ?</h1>
<h2>"If you know something, Say it."</h2>

{# -----------------------------------------Menu horizontal----------------------------------------------#}

<ul>
    <li>
        <button type="button" class="btn btn-primary">
            <div class="texte">
                <a href="{{ 'home' }}" alt="Retour">Retour</a>
            </div>
        </button>
    </li>
    <li class="laUne">
        <button type="button" class="btn btn-primary"><div class="texte">A la une</div></button>
    </li>
    <li>
        <button type="button" class="btn btn-primary"><div class="texte">Sciences</div></button>
    </li>
    <li>
        <button type="button" class="btn btn-primary"><div class="texte">Histoire</div></button>
    </li>
    <li>
        <button type="button" class="btn btn-primary"><div class="texte">Sport</div></button>
    </li>
    <li>
        <button type="button" class="btn btn-primary"><div class="texte">Politiquue</div></button>
    </li>
    <li>
        <button type="button" class="btn btn-primary"><div class="texte">À propos</div></button>
    </li>
    <li>
        <div class="dropdown">
            <input onclick="myFunction()" type="image" id="img_profil2" class="dropbtn"
                   src="pictures/profil.png" alt="">
            <div id="myDropdown" class="dropdown-content">
                {% if app.user %}
                    <a href="{{ path('logout') }}">se déconnecter</a>
                    <a href="{{ path('profile') }}">Voir mon profil</a>
                {% else %}
                    <a href="{{ path('login') }}">se connecter</a>
                {% endif %}
            </div>
        </div>
    </li>
</ul>

{# ----------------------------------------------Article---------------------------------------------------- #}
     <h4>{{ article.title }}</h4>
                {% for image in article.pictures %}
                        <img id="img" src="{{ asset('/uploads/' ~ image.name) }}" alt="Image" width="150">
                {% endfor %}
                <div>{{ article.publicationDate ? article.publicationDate|date('Y-m-d') : '' }}</div>
                <div>{{ article.content }}</div>

        <div id="comments" class="grix xs2 sm3 gutter-0 card">
                <h5 id="liste">Liste des commentaires</h5>
                {% for comment in article.comments %}
                    {% if comment.parent == null %}
                        <div id="commentaire">
                            <h6>Commentaire {{ loop.index }}</h6>
                        </div>
                        <div>
                            <h6> {{ comment.text }} </h6>
                            <p>publié par {{ comment.nickname }} le {{ comment.createdAt|date("d/m/Y H:i") }}</p>
                            <p><a href="#comments_form" data-reply data-id="{{ comment.id }}" class="btn-outline-success">Répondre</a> </p>
                        </div>

                        {% for reply in comment.replies %}
                            <p> réponse publié  par {{ reply.nickname }}  le {{ reply.createdAt|date("d/m/Y H:i") }}</p>
                            <div> <h5> {{ reply.text }}</h5></div>
                        {% endfor %}
                    {% endif %}
                {% endfor %}

            <div class="col-xs2 col-sm3" id="comments_form">
                <h5>Ajouter un commentaire commentaires</h5>
                {{ form(commentForm) }}
            </div>
        </div>
    <div>
        <a id="show" class="btn-danger" href="{{ path('home') }}">back to page home</a>
    </div>
{% endblock %}