src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="articleId", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="date")
     */
    private $publication_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $emergency;

    /**
     * @ORM\OneToMany(targetEntity=Pictures::class, mappedBy="articles", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;


    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $genre;

    /**
     * @ORM\ManyToOne(targetEntity=Journalist::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $journalist;



    public function __construct()
    {
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): self
    {
        $this->publication_date = $publication_date;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;
        return $this;
    }

    public function getEmergency(): ?bool
    {
        return $this->emergency;
    }

    public function setEmergency(bool $emergency): self
    {
        $this->emergency = $emergency;
        return $this;
    }

    /**
     * @return Collection|Pictures[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture  (Pictures $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setArticle($this);
        }
        return $this;
    }

    public function removePicture(Pictures $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getArticle() === $this) {
                $picture->setArticle(null);
            }
        }

        return $this;
    }

    public function setPicture(string $string)
    {
    }


    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment  $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getJournalist(): ?Journalist
    {
        return $this->journalist;
    }

    public function setJournalist(?Journalist $journalist): self
    {
        $this->journalist = $journalist;

        return $this;
    }


}

src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EvenentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenentRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $spaceAvailable;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="evenents")
     * @ORM\JoinColumn(nullable=true)
     */
    private $User;


    public function __construct()
    {
        $this->Participant = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSpaceAvailable(): ?string
    {
        return $this->spaceAvailable;
    }

    public function setSpaceAvailable(string $spaceAvailable): self
    {
        $this->spaceAvailable = $spaceAvailable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('title')
            ->add('content')
            ->add('publication_date')
            ->add('emergency')
            ->add('pictures', FileType::class ,[
                'label'=> false,
                'multiple' => true,
                'mapped' => false,
                'required' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Pictures;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ArticleController extends AbstractController
{
    /**
     * @Route("/article", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $annoncesRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'article' => $annoncesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère les images transmises
            $images = $form->get('pictures')->getData();

            // On boucle sur les images
            foreach($images as $image){
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();

                // On copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // On stocke l'image dans la base de données (son nom)
                $img = new Pictures();
                $img->setName($fichier);
                $article->addPicture($img);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère les images transmises
            $images = $form->get('images')->getData();

            // On boucle sur les images
            foreach($images as $image){
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();

                // On copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // On stocke l'image dans la base de données (son nom)
                $img = new Pictures();
                $img->setName($fichier);
                $article->addPicture($img);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/supprime/image/{id}", name="article_delete_images", methods={"DELETE"})
     */
    public function deleteImage(Pictures $image, Request $request){
        $data = json_decode($request->getContent(), true);

        // On vérifie si le token est valide
        if($this->isCsrfTokenValid('delete'.$image->getId(), $data['_token'])){
            // On récupère le nom de l'image
            $nom = $image->getName();
            // On supprime le fichier
            unlink($this->getParameter('images_directory').'/'.$nom);

            // On supprime l'entrée de la base
            $em = $this->getDoctrine()->getManager();
            $em->remove($image);
            $em->flush();

            // On répond en json
            return new JsonResponse(['success' => 1]);
        }else{
            return new JsonResponse(['error' => 'Token Invalide'], 400);
        }
    }
    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{% extends 'base.html.twig' %}
{% block body%}
{{ form_start(form) }}
    {{ form_widget(form) }}
    {% if app.request.attributes.get('_route') == 'article_edit' %}
        <h2>Images</h2>
        {% for image in article.pictures %}
            <div>
                <img src="{{ asset('/uploads/' ~ image.name) }}" alt="Image" width="150">
                <a href="{{ path('article_delete_images', {id: image.id})}}"
                   data-delete data-token="{{ csrf_token('delete' ~ image.id )}}">Supprimer</a>
            </div>
        {% endfor %}
    {% endif %}
<button id="btn" class="btn-success">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}
{% endblock body%}

templates/article/delete_form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <a id="edit" class="btn-secondary">Delete</a>

</form>
{% endblock %}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}

    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/image.js') }}"></script>
{% endblock %}

templates/article/form.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <link rel="stylesheet" href="{{'public/style.css'}}">
{{ form_start(form) }}

         {% if app.request.attributes.get('_route') == 'article_edit' %}

             <h2>Images Actuelles</h2>

             {% for image in article.pictures  %}
                 <div>
                     <img src="{{ asset('/uploads/' ~ image.name) }}" alt="Image" width="150">

                     <a  class="btn-danger" href="{{ path('delete_image', {id: image.id})}}"
                        data-delete data-token="{{ csrf_token('delete' ~ image.id )}}">Supprimer</a>
                 </div>

             {% endfor %}
         {% endif %}

    <button id="save" class="btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}
{% block body%}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }
        window.onclick = function(event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>

    <div class="body_head">
        <img id="business" src="pictures/business.jpg" alt=""/>
    </div>
    <h1>What happened ?</h1>
    <h2>"If you know something, Say it."</h2>

    {# -----------------------------------------Menu horizontal----------------------------------------------#}

    <ul>
        <li>
            <button type="button" class="btn btn-primary">
                <div class="texte">
                    <a href="{{ 'home' }}" alt="Retour">Retour</a>
                </div>
            </button>
        </li>
        <li class="laUne">
            <button type="button" class="btn btn-primary"><div class="texte">A la une</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Sciences</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Histoire</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Sport</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Politiquue</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">À propos</div></button>
        </li>
        <li>
            <div class="dropdown">
                <input onclick="myFunction()" type="image" id="img_profil2" class="dropbtn"
                       src="pictures/profil.png" alt="">
                <div id="myDropdown" class="dropdown-content">
                    {% if app.user %}
                        <a href="{{ path('logout') }}">se déconnecter</a>
                        <a href="{{ path('profile') }}">Voir mon profil</a>
                    {% else %}
                        <a href="{{ path('login') }}">se connecter</a>
                    {% endif %}
                </div>
            </div>
        </li>
    </ul>

{# --------------------------- #}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Publication_date</th>
                <th>Title</th>
                <th>Content</th>
                <th>Emergency</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in article %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.publicationDate ? article.publicationDate|date('Y-m-d') : '' }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.content }}</td>
                <td>{{ article.emergency ? 'Yes' : 'No' }}</td>
                <td>
                    <a class="btn btn-outline-info" href="{{ path('article_show', {'id': article.id}) }}">show</a>
                    <a class="btn btn-outline-danger" href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a id="create" class="btn btn-success" href="{{ path('article_new') }}">Create new</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}
{% block body%}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }
        window.onclick = function(event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>

    <div class="body_head">
        <img id="business" src="pictures/business.jpg" alt=""/>
    </div>
    <h1>Create new article </h1>
    <h2>"If you know something, Say it."</h2>

    {# -----------------------------------------Menu horizontal----------------------------------------------#}

    <ul>
        <li>
            <button type="button" class="btn btn-primary">
                <div class="texte">
                    <a href="{{ 'home' }}" alt="Retour">Retour</a>
                </div>
            </button>
        </li>
        <li class="laUne">
            <button type="button" class="btn btn-primary"><div class="texte">A la une</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Sciences</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Histoire</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Sport</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">Politiquue</div></button>
        </li>
        <li>
            <button type="button" class="btn btn-primary"><div class="texte">À propos</div></button>
        </li>
        <li>
            <div class="dropdown">
                <input onclick="myFunction()" type="image" id="img_profil2" class="dropbtn"
                       src="pictures/profil.png" alt="">
                <div id="myDropdown" class="dropdown-content">
                    {% if app.user %}
                        <a href="{{ path('logout') }}">se déconnecter</a>
                        <a href="{{ path('profile') }}">Voir mon profil</a>
                    {% else %}
                        <a href="{{ path('login') }}">se connecter</a>
                    {% endif %}
                </div>
            </div>
        </li>
    </ul>

    <div id="form">
        {{ include('article/_form.html.twig') }}
    </div>

    <a id="back" class="btn btn-secondary" href="{{ path('article_index') }}">back to list</a>

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Publication_date</th>
                <td>{{ article.publicationDate ? article.publicationDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ article.content }}</td>
            </tr>
            <tr>
                <th>Emergency</th>
                <td>{{ article.emergency ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('article_index') }}">back to list</a>

    <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}